swagger: "2.0"
info:
  description: "Luni Customer Api"
  version: "1.0.0"
  title: "Luni Api"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "raviraj23sep@yahoo.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/luni"
schemes:
- "https"
- "http"
consumes:
  - application/json
produces:
  - application/json
paths:
  /customer:
    post:
      tags:
      - "Customer"
      summary: "Add a new customer to the app"
      description: ""
      operationId: "addCustomer"
      parameters:
      - in: "body"
        name: "body"
        description: "Customer object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Customer"
      responses:    
        "200":
          description: successful operation
          schema:
              $ref: "#/definitions/Customer"
        "404":
          description: Customer data not found
          schema:
            $ref: '#/definitions/Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'    
        default:
          description: Error
          schema:
            $ref: '#/definitions/Error'
    put:
      tags:
      - "pet"
      summary: "Add a new customer to the app"
      description: ""
      operationId: "updateCustomer"
      parameters:
      - in: "body"
        name: "body"
        description: "Customer object that needs to be updated to the store"
        required: true
        schema:
          $ref: "#/definitions/Customer"
      responses:    
        "200":
          description: successful operation
          schema:
              $ref: "#/definitions/Customer"
        "404":
          description: Could not find Customer with the providedID 
          schema:
            $ref: '#/definitions/Error'
        "500":
          description: Could not update 
          schema:
            $ref: '#/definitions/Error'     
        default:
          description: Error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Customer:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      customerName:
        type: "string"
      city:
        type: "string"
      address:
        type: "string"
      contactPhone:
        type: "string"
      email:
        type: "boolean"
      confirmationCode:
        type: "string"
      password:
        type: "string"
      timeJoined:
        type: "string"
        format: "date-time"
      addressList:
        type: "array"
        items: 
         $ref: '#/definitions/Address'
      fevRestaurents:
        type: "array"
        items: 
          type: "string"
  Address:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      addressType: 
        type: "string"
      houseNo:
        type: "string"
      sector:
        type: "string"  
      city:
        type: "string"
      isDefault:
        type: "boolean"
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      field:
        type: string      